### ISSUE TITLE
Fix writing to csv for list 

### ISSUE THREAD

**Issue by hhunterzinck** [Sage-Bionetworks/synapsemonitor#34]
Currently, tries to write the output of monitoring to a csv but prints out an error because the to_csv doesn't work for a list.

**Comment by thomasyu888** [comment]
Should it be `synapsesmonitor find-modified-entities` instead of `monitor`?  Or... eventually will it be:

```
synapseaction monitor ...
synapseaction notify ...
```

**Comment by hhunterzinck** [comment]
Parallel structure is ideal and the more concise the better.  But is the above comment referencing this issue?
