### ISSUE TITLE
Remove create-file-view command functionality?

### ISSUE THREAD

**Issue by hhunterzinck** [Sage-Bionetworks/synapsemonitor#46]
Is this worth retaining and maintaining if single entities and containers can be monitored? For efficiency in monitoring a large container's contents, synapsemonitor could create a temporary project and file view under the hood instead of making the user to create one in a separate command.

**Comment by thomasyu888** [comment]
I think ideally this feature could be added to the synapse client.  Basically before we added support for the single entity / container, I wanted to scope the "monitoring" to only be for fileviews. 

Essentially the workflow would be:

1. I have a project I have to monitor
2. Do I have a fileview?  if not, run create-file-view
3. Monitor fileview

**Comment by hhunterzinck** [comment]
Sure, let's keep it for now.
