### ISSUE TITLE
Functionality to track users of synapse teams

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapsemonitor#63]
Thoughts about this concept? Draft PR in #8

**Comment by thomasyu888** [comment]
I'm tempted to say that this is out of scope for this package.  That being said, it would be nice if there was a mechanism to track when users joined a team.

**Comment by hhunterzinck** [comment]
I'd vote for tracking and monitoring teams on Synapse in a separate package.  `synapse-team-monitor`?

That said, being able to specify a team to notify, instead of a list of individual users, of a modified Synapse entity could be very useful.  What do you think?

**Comment by thomasyu888** [comment]
Agreed with both. Lets open a ticket to specify a team to notify.
